// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABkBdLx2p3VpUY8G1ZM3SLgy-mBT1aD7U',
    appId: '1:1085982793073:web:3aeee2b0e3d3519967ead0',
    messagingSenderId: '1085982793073',
    projectId: 'flutter-sample-project-318a4',
    authDomain: 'flutter-sample-project-318a4.firebaseapp.com',
    storageBucket: 'flutter-sample-project-318a4.appspot.com',

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG2cCYXgA515-qoDHA8DV9X0VLJl9Htm4',
    appId: '1:1085982793073:android:36f1916847e9ec9d67ead0',
    messagingSenderId: '1085982793073',
    projectId: 'flutter-sample-project-318a4',
    storageBucket: 'flutter-sample-project-318a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCFBlKK7M-_9US7N7jiSVu-l1gj7xSQdc',
    appId: '1:1085982793073:ios:5d62d42182614eca67ead0',
    messagingSenderId: '1085982793073',
    projectId: 'flutter-sample-project-318a4',
    storageBucket: 'flutter-sample-project-318a4.appspot.com',
    iosBundleId: 'com.example.flutterTestings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCFBlKK7M-_9US7N7jiSVu-l1gj7xSQdc',
    appId: '1:1085982793073:ios:5d62d42182614eca67ead0',
    messagingSenderId: '1085982793073',
    projectId: 'flutter-sample-project-318a4',
    storageBucket: 'flutter-sample-project-318a4.appspot.com',
    iosBundleId: 'com.example.flutterTestings',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABkBdLx2p3VpUY8G1ZM3SLgy-mBT1aD7U',
    appId: '1:1085982793073:web:a0ee5064cc8dfd3267ead0',
    messagingSenderId: '1085982793073',
    projectId: 'flutter-sample-project-318a4',
    authDomain: 'flutter-sample-project-318a4.firebaseapp.com',
    storageBucket: 'flutter-sample-project-318a4.appspot.com',
  );
}
